apiVersion: v1
kind: Service
metadata:
  name: apollo-gateway
  namespace: apollo
  labels:
    app: apollo-gateway
spec:
  type: ClusterIP
  selector:
    app: apollo-gateway
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
    name: graphql
